### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by noandrea** [aeternity/tool-paperwallets#1]
- [ ] generate N wallets  and charge each wallet with 1 token
- [ ] generate the short url for the address 
            SHORT: s.aepps.com/xyz
            LONG  : beer.aepps.com?k=X&p=Y
- [ ] generate the QR code for SHORT (pdf?)
